version: '3.8'

services:

  mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d